[package]
name = "fontdue-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
fontdue = "^0.7.3"
libc = "0.2"
cty = "0.2"

[build-dependencies]
cbindgen = "0.24"
